version: '3.7'

services:
  if50-backend:
    image: ${DOCKER_PREFIX:-ibn40}/fleet50-backend:${DOCKER_TAG:-latest}
    build:
      context: ./backend
    ports:
    - "4001:4001"
    env_file:
      - .env
    environment:
      - ENV=${ENV:-dev}
  if50-frontend:
    image: ${DOCKER_PREFIX:-ibn40}/fleet50-frontend:${DOCKER_TAG:-latest}
    build:
      context: ./frontend
    ports:
    - "3001:3001"