apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      component: scorpio
  name: scorpio
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scorpio
  strategy: {}
  template:
    metadata:
      labels:
        component: scorpio
    spec:
      containers:
      - image: scorpiobroker/all-in-one-runner:java-kafka-latest
        imagePullPolicy: ""
        name: scorpio
        ports:
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}