apiVersion: v1
kind: Service
metadata:
  labels:
      component: scorpio
  name: scorpio-node-port
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    component: scorpio